### ISSUE TITLE
Support for CA when you use certURL

### ISSUE THREAD

**Issue by villadalmine** [bakito/sealed-secrets-web#195]
Hi,

Im using certURL but i have this error.

2023/11/14 11:42:22 Connection to sealed secrets with (Cert URL: https://ss.xx.xx/v1/cert.pem)2023/11/14 11:42:23 Setup sealer: Get "https://ss.xx.cxx/v1/cert.pem": tls: failed to verify certificate: x509: certificate signed by unknown authority

It is an internal company CA, so normally we add root CA in the pod, does it possible to add this feature to the pod ? or just avoid and use insecure

Regards
Rino

**Comment by bakito** [comment]
You can mount your own ca into the pod by using volume and volumeMounts and mount it to /etc/ssl/certs/ca-certificates.crt

**Comment by villadalmine** [comment]
> You can mount your own ca into the pod by using volume and volumeMounts and mount it to /etc/ssl/certs/ca-certificates.crt

indeed!! i totally forget it!! thanks for reminder !! i guess your recommendation is based in the distro supported in the main app.

**Comment by villadalmine** [comment]
> You can mount your own ca into the pod by using volume and volumeMounts and mount it to /etc/ssl/certs/ca-certificates.crt

I need to modify the helm chart i guess...

**Comment by bakito** [comment]
Only your values for the helm chart

**Comment by villadalmine** [comment]
> /etc/ssl/certs/ca-certificates.crt

looks like i need to understand how is parsing the values

```
volumeMounts: 
  - name: sealed-secrets-web-tst-blue
    mountPath: /etc/ssl/certs/ca-certificates.crt
# -- Additional volumes to the image updater pod
volumes:
  - name: sealed-secrets-web-tst-blue
    secret: 
      scretName: sealed-secrets-web-tst-secret
```


i created the secret manually, well i have my crt

does it ok ?


`one or more objects failed to apply, reason: Deployment.apps "sealed-secrets-web-tst-blue-se" is invalid: [spec.template.spec.volumes[0].secret.secretName: Required value, spec.template.spec.containers[0].volumeMounts[0].name: Not found: "sealed-secrets-web-tst-blue"]. Retrying attempt #3 at 2:20PM.`

**Comment by villadalmine** [comment]
> > /etc/ssl/certs/ca-certificates.crt
> 
> looks like i need to understand how is parsing the values
> 
> ```
> volumeMounts: 
>   - name: sealed-secrets-web-tst-blue
>     mountPath: /etc/ssl/certs/ca-certificates.crt
> # -- Additional volumes to the image updater pod
> volumes:
>   - name: sealed-secrets-web-tst-blue
>     secret: 
>       scretName: sealed-secrets-web-tst-secret
> ```
> 
> i created the secret manually, well i have my crt
> 
> does it ok ?
> 
> `one or more objects failed to apply, reason: Deployment.apps "sealed-secrets-web-tst-blue-se" is invalid: [spec.template.spec.volumes[0].secret.secretName: Required value, spec.template.spec.containers[0].volumeMounts[0].name: Not found: "sealed-secrets-web-tst-blue"]. Retrying attempt #3 at 2:20PM.`

mmm

Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/var/lib/kubelet/pods/2b6f2f81-d324-4ab2-b21b-033d8858f899/volumes/kubernetes.io~secret/sealed-secrets-web-tst-blue" to rootfs at "/etc/ssl/certs/ca-certificates.crt": mount /var/lib/kubelet/pods/2b6f2f81-d324-4ab2-b21b-033d8858f899/volumes/kubernetes.io~secret/sealed-secrets-web-tst-blue:/etc/ssl/certs/ca-certificates.crt (via /proc/self/fd/6), flags: 0x5001: not a directory: unknown

i was able, i had a typo in my config.. but now another issue.. debugging

**Comment by villadalmine** [comment]
i saw you are using FROM alpine:latest, i guess it is not best option for production env using latest image..
but just curios why blocked me to add the certificate when alpine uses /etc/ssl/certs/ca-certificates.crt...

any idea ?

**Comment by villadalmine** [comment]
Please, you can close it, i tried a lot and never update the certificate because i need to run init-container to do the update-ca-certificates, get root permission in context, adding only it is not possible because the /etc/ssl/certs/ca-certificates.crt is created in the image after update-ca-certificates or when you update or do dkpkg-reconfigure for ca.  Thanks for your time. I will use just pure command line, i know developer are lazzy and want everything with UI :(

**Comment by bakito** [comment]
What's the name/key of the secret entry for the ca file?

It must be `ca-certificates.crt`  and then the volume mount:

```
volumeMounts: 
  - name: sealed-secrets-web-tst-blue
      mountPath: /etc/ssl/certs
      readOnly: true
```
Like that the default ca is replaced in the pod.

If you can't rename the secret entry , use subPath in the mount.

**Comment by villadalmine** [comment]
> What's the name/key of the secret entry for the ca file?
> 
> It must be `ca-certificates.crt` and then the volume mount:
> 
> ```
> volumeMounts: 
>   - name: sealed-secrets-web-tst-blue
>       mountPath: /etc/ssl/certs
>       readOnly: true
> ```
> 
> Like that the default ca is replaced in the pod.
> 
> If you can't rename the secret entry , use subPath in the mount.

i tested but fail due security issues, pod it does not have permission to write that file

**Comment by villadalmine** [comment]
> What's the name/key of the secret entry for the ca file?
> 
> It must be `ca-certificates.crt` and then the volume mount:
> 
> ```
> volumeMounts: 
>   - name: sealed-secrets-web-tst-blue
>       mountPath: /etc/ssl/certs
>       readOnly: true
> ```
> 
> Like that the default ca is replaced in the pod.
> 
> If you can't rename the secret entry , use subPath in the mount.

Thanks for your patience and help... cert was mounted, but im still having issues with health check, not sure what is trying to do, no so much log.

2023/11/17 08:02:40 Connection to sealed secrets with (Cert URL: https://ss.xxxx/v1/cert.pem)
2023/11/17 08:02:40 Running sealed secrets web (v3.1.3) on port 8080

i commented that part

```
deployment:
#   # -- Readiness Probes
#   readinessProbe:
#     failureThreshold: 3
#     # periodSeconds: 5
#     # successThreshold: 1
#     # timeoutSeconds: 10
#     # initialDelaySeconds: 30
#     httpGet:
#       path: /_health
#       port: http

#   # -- Liveness Probes
#   livenessProbe:
#     failureThreshold: 3
#     # periodSeconds: 10
#     # successThreshold: 1
#     # timeoutSeconds: 10
#     # initialDelaySeconds: 15
#     httpGet:
#       path: /_health
#       port: http

sealedSecrets:
  # # -- Namespace of the sealed secrets service
  # namespace: ca43-sealed-secrets
  # # -- Name of the sealed secrets service
  # serviceName: sealed-secrets-tst-blue-se
  certURL: "https://ss.xxx/v1/cert.pem"

and i added

deployment:

  args:
    defaultArgsEnabled: false
    additionalArgs:
    - --enable-web-logs
    - --sealed-secrets-cert-url=https://ss.xxx/v1/cert.pem
    
```


what is waiting the app ??
