### ISSUE TITLE
Custom initial secret file has comments removed

### ISSUE THREAD

**Issue by trevorlauder** [bakito/sealed-secrets-web#56]
The default `secret.yaml` file has and shows the comments in the UI.  When using a custom yaml file, those comments are removed.

It would be nice to be able to show comments in a custom initial yaml secret.

**Comment by bakito** [comment]
Hi @trevorlauder 

Could you please provide more content.
- how did you setup?
- how is the config/values.yaml?
- how does your secret.yaml look like?

Thank you

Cheers Marc

**Comment by trevorlauder** [comment]
We're using our own chart as the one included here doesn't meet our requirements, so I can't give you a `values.yaml` that you would expect.

```
args:
  - --disable-load-secrets
  - --format=yaml
  - --initial-secret-file=/default-secret/secret.yaml
```

The initial secret is put in place with a ConfigMap and the file contents are correct.  It looks like when Go is processing the YAML, it's stripping the comments.

```yaml
---
apiVersion: v1
kind: Secret
metadata:
# some comments
# some more comments
  name: my-name
  namespace: my-namespace
stringData:
  mySecret: my value
type: Opaque
```

The UI shows

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-name
  namespace: my-namespace
stringData:
  mySecret: my value
type: Opaque
```
