### ISSUE TITLE
Making reference to Controller in a different namespace than kube-system

### ISSUE THREAD

**Issue by hutger** [bakito/sealed-secrets-web#66]
Hi There, 

My controller is currently installed at _sealed-secrets_ namespace. On trying to seal a secret, I get an error:

`{ "error": "cannot get sealed secret service: services \"sealed-secrets\" is forbidden: User \"system:serviceaccount:sealed-secrets:sealed-secrets-web\" cannot get resource \"services\" in API group \"\" in the namespace \"kube-system\"" } `

It seems that _sealed-secrets-web_ is looking for a secret at kube-system.

It there way to point the app to controller in a different namespace than kube-system?

Thanks in advance.

**Comment by bakito** [comment]
Hi @hutger 

Please see the response in https://github.com/bakito/sealed-secrets-web/issues/47#issuecomment-1161268259

**Comment by hutger** [comment]
Hi @bakito , thanks for point me out to the thread.

But it seems that my use case is somehow different. Please correct me if I'm wrong.

The thread #47 is regard the need of having _sealed-secrets-controller_ and _sealed-secrets-web_ as part of the same namespace. 

In the situation I'm facing, the controller and web are already sharing the same namespace (_sealed-secrets_), but _sealed-secrets-web_ is looking for the controller at _kube-system_ instead.

I'm wondering why it's looking for the controller in _kube-system_ and where I can set _sealed-secrets_ namespace as the controller location.

**Comment by hutger** [comment]
Hi @bakito, 

I'm setting a NGINX rule for pointing to a different path than /. 

You can see the defs below:
```
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: 'false'
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    # -- Ingress hosts
    hosts:
      - host: my-domain.com
        paths:
          - path: /sealed-secrets(/|$)(.*)
            pathType: Prefix
```

I'm getting the following error trying to open the page:

```
Sealed Secrets Encode Decode Seal Secret
Sealed Secret
Secrets {{sec.name}} {{sec.namespace}} {{error}} Close Sealed Secrets Web (v2.8.2) mdi-github
```
I understand that the error is related to this Ticket, but I'm wondering if the regex is applicable to sealed-secrets-web. I'm using it for other tools (e.g. ArgoCD, Longhorn,...) and works fine. 

I'm asking because if the path points to /, the WebUI opens, even with the error message being displayed.

**Comment by bakito** [comment]
> Hi @bakito,
> 
> I'm setting a NGINX rule for pointing to a different path than /.
> 
> You can see the defs below:
> 
> ```
> ...
>     annotations:
>       nginx.ingress.kubernetes.io/ssl-redirect: 'false'
>       nginx.ingress.kubernetes.io/use-regex: "true"
>       nginx.ingress.kubernetes.io/rewrite-target: /$2
>     # -- Ingress hosts
>     hosts:
>       - host: my-domain.com
>         paths:
>           - path: /sealed-secrets(/|$)(.*)
>             pathType: Prefix
> ...
> ```
> 
> I'm getting the following error trying to open the page:
> 
> ```
> Sealed Secrets Encode Decode Seal Secret
> Sealed Secret
> Secrets {{sec.name}} {{sec.namespace}} {{error}} Close Sealed Secrets Web (v2.8.2) mdi-github
> ```
> 
> I understand that the error is related to this Ticket, but I'm wondering if the regex is applicable to sealed-secrets-web. I'm using it for other tools (e.g. ArgoCD, Longhorn,...) and works fine.
> 
> I'm asking because if the path points to /, the WebUI opens, even with the error message being displayed.

@hutger what does this have to do with the upper comments?

**Comment by bakito** [comment]
> Hi @bakito , thanks for point me out to the thread.
> 
> But it seems that my use case is somehow different. Please correct me if I'm wrong.
> 
> The thread #47 is regard the need of having _sealed-secrets-controller_ and _sealed-secrets-web_ as part of the same namespace.
> 
> In the situation I'm facing, the controller and web are already sharing the same namespace (_sealed-secrets_), but _sealed-secrets-web_ is looking for the controller at _kube-system_ instead.
> 
> I'm wondering why it's looking for the controller in _kube-system_ and where I can set _sealed-secrets_ namespace as the controller location.

@hutger can you please provide more information.

How dis you install sealed secrets web? 
- helm values
- what ar the args you have in your deployment?

**Comment by hutger** [comment]
> 
@bakito , 

Here it is:

name: sealed-secrets-web
version: 2.8.2
repository: https://bakito.github.io/helm-charts

Please find the values file:

```
includeLocalNamespaceOnly: false
disableLoadSecrets: true
format: yaml
image:
  args:
    - "--kubeseal-arguments=--controller-name=sealed-secrets"
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: "nginx"

  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2

  hosts:
    - host: my-domain.com
      paths:
        - path: /sealed-secrets(/|$)(.*)
          pathType: Prefix

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
```
