### ISSUE TITLE
Nginx rewrite rules not working

### ISSUE THREAD

**Issue by hutger** [bakito/sealed-secrets-web#68]
Hi @bakito,

I'm setting a NGINX rule for pointing to a different path than /.

You can see the defs below:
```
...
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: 'false'
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    # -- Ingress hosts
    hosts:
      - host: my-domain.com
        paths:
          - path: /sealed-secrets(/|$)(.*)
            pathType: Prefix
...
```
I'm getting the following error trying to open the page:
```
Sealed Secrets Encode Decode Seal Secret
Sealed Secret
Secrets {{sec.name}} {{sec.namespace}} {{error}} Close Sealed Secrets Web (v2.8.2) mdi-github
```

By any chance, have you came across this use case?

**Comment by bakito** [comment]
Hi @hutger 

Can you try to set the arg "--web-external-url" with the external URL of your ingress?

https://github.com/bakito/sealed-secrets-web/blob/43efe9bc63a0a49fa679fda81a632a555cc8190d/pkg/config/types.go#L19

**Comment by hutger** [comment]
> 

Hi @bakito , really appreciated... didn't know about this option.

I've tried the definitions below and it won't work.
```
...
image:
  args:
    - "--kubeseal-arguments=--controller-name=sealed-secrets --controller-namespace=sealed-secrets --web-external-url=http://my-domain.com/sealed-secrets"
...
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: 'false'
      # nginx.ingress.kubernetes.io/use-regex: "true"
      # nginx.ingress.kubernetes.io/rewrite-target: /$2
    # -- Ingress hosts
    hosts:
      - host: my-domain.com
        paths:
          - path: /sealed-secrets    # (/|$)(.*)
            pathType: Prefix
...
```

Have tried also other combinations... none seems to work.
- With Rewrite rule enabled
- web-external-url with and without /sealed-secrets

**Comment by bakito** [comment]
try 
```
  args:
    - "--kubeseal-arguments=--controller-name=sealed-secrets --controller-namespace=sealed-secrets"
    - "--web-external-url=http://my-domain.com/sealed-secrets"
```

**Comment by hutger** [comment]
> 
No luck... It didn't work.

```
...
image:
  args:
    - "--kubeseal-arguments=--controller-name=sealed-secrets --controller-namespace=sealed-secrets"
    - "--web-external-url=http://my-domain.com/sealed-secrets"
...
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: 'false'
      # nginx.ingress.kubernetes.io/use-regex: "true"
      # nginx.ingress.kubernetes.io/rewrite-target: /$2
    # -- Ingress hosts
    hosts:
      - host: my-domain.com
        paths:
          - path: /sealed-secrets    # (/|$)(.*)
            pathType: Prefix
...
```

**Comment by bakito** [comment]
Can you please check the html of the webpage?
There are some URL like https://github.com/bakito/sealed-secrets-web/blob/main/templates/index.html#L163
https://github.com/bakito/sealed-secrets-web/blob/main/templates/index.html#L84-L87

Do these URL match your ingress?

**Comment by bakito** [comment]
@hutger I might have found something.
Could you please try with the latest main image `ghcr.io/bakito/sealed-secrets-web:main` and args
```
 args:
    - "--kubeseal-arguments=--controller-name=sealed-secrets --controller-namespace=sealed-secrets"
    - "--web-external-url=sealed-secrets"
```
and ingress config:
```
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"

...

    hosts:
      - host: my-domain.com
        paths:
          - path: /sealed-secrets(/|$)(.*)
            pathType: Prefix

```

**Comment by bakito** [comment]
@hutger the release https://github.com/bakito/sealed-secrets-web/releases/tag/v2.8.3 contains this change

**Comment by hutger** [comment]
@bakito , 

After upgrading to version 2.8.3, it's working like a charm with the definitions below, just for future references using Helm:

_Chart.yaml_
```
apiVersion: v2
name: sealed-secrets
version: 1.0.1
dependencies:
  - name: sealed-secrets
    version: 2.6.1
    repository: https://bitnami-labs.github.io/sealed-secrets
  - name: sealed-secrets-web
    version: 2.8.3
    repository: https://bakito.github.io/helm-charts
```

_values.yaml_
````
# Reference: https://artifacthub.io/packages/helm/bitnami-labs/sealed-secrets
sealed-secrets:
  keyrenewperiod: "" # Default 30 days

# Reference: https://artifacthub.io/packages/helm/bakito/sealed-secrets-web
sealed-secrets-web:
  includeLocalNamespaceOnly: false
  disableLoadSecrets: true
  format: yaml
  image:
    args:
      - "--kubeseal-arguments=--controller-name=sealed-secrets --controller-namespace=sealed-secrets"
      - "--web-external-url=http://my.domain.com/sealed-secrets"
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    className: "nginx"

    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: 'false'
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/rewrite-target: /$2  

    hosts:
      - host: my.domain.com
        paths:
          - path: /sealed-secrets(/|$)(.*)
            pathType: Prefix

    defaultTls: false
    tls: [ ]
    
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
``` 

Thanks for your great support.
