### ISSUE TITLE
Enabling TLS

### ISSUE THREAD

**Issue by hutger** [bakito/sealed-secrets-web#70]
@bakito , 

Any tip on enabling SSL?

```
    hosts:
      - host: my-domain.com
        paths:
          - path: /sealed-secrets(/|$)(.*)
            pathType: Prefix

    defaultTls: false

    tls:
      hosts: [ my-domain.com ]
      secretName: sealed-secrets-web-tls
```

This one does not seem to work.

**Comment by bakito** [comment]
It's 

```
    tls:
     -  hosts: [ my-domain.com ]
        secretName: sealed-secrets-web-tls
```

**Comment by hutger** [comment]
> It's
> 
> ```
>     tls:
>      -  hosts: [ my-domain.com ]
>         secretName: sealed-secrets-web-tls
> ```

Oh gosh, I've looked at the templates and realised my mistake. 

It works perfectly. 

Just for other users' reference:

```
...
image:
  args:
    - "--kubeseal-arguments=--controller-name=sealed-secrets --controller-namespace=sealed-secrets"
    - "--web-external-url=https://my-domain.com/sealed-secrets"
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: "nginx"
  # -- Ingress annotations
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2

  hosts:
    - host: my-domain.com
      paths:
        - path: /sealed-secrets(/|$)(.*)
          pathType: Prefix

  tls:
    - hosts: [ my-domain.com ]
      secretName: sealed-secrets-web-tls
...
```

Thanks once again.

**Comment by hutger** [comment]
> It's
> 
> ```
>     tls:
>      -  hosts: [ my-domain.com ]
>         secretName: sealed-secrets-web-tls
> ```

Oh gosh, I've looked at the templates and realised my mistake. 

It works perfectly. 

Just for other users' reference:

```
...
image:
  args:
    - "--kubeseal-arguments=--controller-name=sealed-secrets --controller-namespace=sealed-secrets"
    - "--web-external-url=https://my-domain.com/sealed-secrets"
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: "nginx"
  # -- Ingress annotations
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2

  hosts:
    - host: my-domain.com
      paths:
        - path: /sealed-secrets(/|$)(.*)
          pathType: Prefix

  tls:
    - hosts: [ my-domain.com ]
      secretName: sealed-secrets-web-tls
...
```
